pipeline {
    agent any
    environment {
        REGION = "ap-south-1"
        ECR_URI = "<your-ecr-uri>"
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/staragile2016/OnlineTicketPlatform-BMS.git'
            }
        }
        stage('Build Image') {
            steps {
                dir('bookmyshow-app') {
                    sh 'docker build -t bms-app .'
                }
            }
        }
        stage('Push to ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ECR_URI}
                docker tag bms-app:latest ${ECR_URI}:latest
                docker push ${ECR_URI}:latest
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                aws eks update-kubeconfig --region ${REGION} --name bms-cluster
                kubectl apply -f kubernetes/
                '''
            }
        }
    }
}
